### ISSUE TITLE
IE 11 issue - const is not initialized

### ISSUE THREAD

**Issue by RaulTsc** [jonschlinkert/clone-deep#15]
for (const breaks in IE 11 - it throws an error that 'Const is not initialised'. Using var or let works

http://kangax.github.io/compat-table/es6/

Thanks!

**Comment by NJWong** [comment]
Hi, I've raised a PR here: https://github.com/jonschlinkert/clone-deep/pull/16

**Comment by arielhenryson** [comment]
This is not the solution if you are using ECMAScript > 5 you are using technology that are not supported in IE11 out of the box. You have to use something like BabelJS to transpile your code to ECMAScript 5 code. The right solution will be to continue use "edge" technology but to publish to NPM code that is compatibility with older browser, because project that is built for example with Angular CLI expect that the code that are not from the project (node_modules) will be ready for production and therefore do not included in the internal transpiling process of the app

**Comment by AndrewBogdanovTSS** [comment]
@arielhenryson ++
I try to use clone-deep in my Vue/Nuxt project and since default webpack config is set to exclude `node_modules` from transpilation I'm getting an error in IE11 and Safari 10

**Comment by jonschlinkert** [comment]
sorry for the late reply. I'll try to get the pr merged in asap.

**Comment by AndrewBogdanovTSS** [comment]
@jonschlinkert I hope it will be more asap promise than the one you gave on 28 of August

**Comment by jonschlinkert** [comment]
> I hope it will be more asap promise than the one you gave on 28 of August

No, it will be the same kind of promise that I give for all the things that I do with my own free time.

**Comment by NJWong** [comment]
Thanks @jonschlinkert - appreciate you taking the time to look into this 👍

**Comment by jonschlinkert** [comment]
resolved

**Comment by AndrewBogdanovTSS** [comment]
Was this fix released?
