### ISSUE TITLE
- error ./node_modules/clone-deep/utils.js Cannot statically analyse 'require(…, …)' in line 7

### ISSUE THREAD

**Issue by kpripper** [jonschlinkert/clone-deep#27]
Next.js is up to date (13.4.4)

Failed to compile

./node_modules/clone-deep/utils.js
Cannot statically analyse 'require(…, …)' in line 7

Import trace for requested module:
./node_modules/clone-deep/utils.js
./node_modules/clone-deep/index.js
./node_modules/merge-deep/index.js
./node_modules/puppeteer-extra-plugin/dist/index.cjs.js
./node_modules/puppeteer-extra-plugin-recaptcha/dist/index.cjs.js
./src/app/(server)/api/parser/route.js

**Comment by jonschlinkert** [comment]
Sorry for the late reply, that looks like it's related to an older version of clone-deep, as this project no longer has a `utils.js` file in it. I'm going to go ahead and close due to the age of the issue, and since we haven't had any other comments on this. Feel free to open another issue if you or someone else experiences this again.

**Comment by zkSoju** [comment]
I am getting this still. Any resolution?

**Comment by yo1nick** [comment]
The problem is not from the clone-deep module but from puppeteer-extra-plugin which uses merge-deep which in turn uses a very old version of clone-deep (0.2.4)
 A solution for this problem can be found here: https://github.com/berstend/puppeteer-extra/issues/829#issuecomment-1691086606
