### ISSUE TITLE
[Question] How to use this in Angular 4?

### ISSUE THREAD

**Issue by kamlekar** [jonschlinkert/clone-deep#7]
Please help me to import this module in Angular 4 project.

Currently, I tried the following:

    import { cloneDeep } from 'clone-deep';

But this throws error on runtime saying;

> ERROR TypeError:Object(...) is not a function

**Comment by doowb** [comment]
You might be able to do `import * as cloneDeep from 'clone-deep';` but I'm not positive on the syntax.

You should still be able to use `require` by doing `const cloneDeep = require('clone-deep');` if the `import` statement isn't working.

Since this is just a node module, you can search for information on how to import node modules into angular 4. Also, ask on Stack Overflow since it's a general question and there are probably more answers there.

I'm going to close the issue, but if you find a bug while using this library, please feel free to open another issue.

**Comment by kamlekar** [comment]
Thanks for your helpful comment.

After some research, I ended up using custom build of lodash which actually supports by angular4.

    Import { cloneDeep } from 'lodash';

This as I know would get only `cloneDeep` functionality. I hope I am doing right.
